import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Navbar from "./components/Navbar/Navbar";

import LoginModal from "./components/modals/LoginModal";
import RegisterModal from "./components/modals/RegisterModal";
import ToastContainerBar from "./components/ToastContainerBar";
import { CounterContextProvider } from "./context/counter.context";
import { ShoppingCartProvider } from "./context/shopincartConext";
import Provider from "./components/Provider";
import Footer from "./components/Footer/Footer";
import { WixClientContextProvider } from "./context/wixcontext";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* Integrating Google Analytics for tracking. */}
        {/* <GoogleAnalytics GA_MEASUREMENT_ID={process.env.GA_MEASUREMENT_ID} /> */}
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={inter.className}>
        <Provider>
          {/* 
          <CounterContextProvider>
            <ShoppingCartProvider> */}
          <WixClientContextProvider>
            <ToastContainerBar />
            <LoginModal />
            <RegisterModal />
            <Navbar />
            {children}
            {/* <Footer /> */}
            {/* </ShoppingCartProvider>
          </CounterContextProvider>
   */}
          </WixClientContextProvider>
        </Provider>
      </body>
    </html>
  );
}
