import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Provider from "./components/Provider";
import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/Footer/Footer";
import LoginModal from "./components/modals/LoginModal";
import RegisterModal from "./components/modals/RegisterModal";
import ToastContainerBar from "./components/ToastContainerBar";
import { CounterContextProvider } from "./context/counter.context";
import { ShoppingCartProvider } from "./context/shopincartConext";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <CounterContextProvider>
            <ShoppingCartProvider>
              <ToastContainerBar />
              <LoginModal />
              <RegisterModal />
              <Navbar />
              {children}
              <Footer />
            </ShoppingCartProvider>
          </CounterContextProvider>
        </Provider>
      </body>
    </html>
  );
}
